version: '3'
# Volumes
volumes:
  database_data:
    driver: local
# Services
services:
  # Database 
  # PostgreSQL - postgres_db
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: cion-dev
      POSTGRES_PASSWORD: cionDevDB
      POSTGRES_DB: public
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql